# Night Watch planner API
swagger: '2.0'
info:
  title: Night Watch Planner API
  description: Planner to optimize Night Watchs in RPGs
  version: "0.1.0"
host: localhost:3000
schemes:
  - http
basePath: /v1
produces:
  - application/json
paths:
  /optimize:
    post:
      summary: Proposes a night watch plan for a party of adventurers.
      description: Proposes a night watch plan for a party of adventurers.
      operationId: generatePlan
      parameters:
        - name: planRequest
          in: body
          description: Details of the plan request.
          required: true
          schema:
            $ref: '#/definitions/PlanRequest'

      produces:
        - application/json
      responses:
        200:
          description: Night watches proposal for the party
          schema:
            $ref: '#/definitions/Plan'
        400:
          description: Bad request
          schema:
            properties:
              message:
                type: string
                description: Error message
definitions:
  Sense:
    description: Relevant senses that allows a _PC_ to be aware of intruders at a relevant distance.
    type: string
    default: Normal
    enum:
      - Blindsight
      - Darkvision
      - Low light
      - Normal
      - Scent

  Character:
    properties:
      name:
        type: string
      senses:
        type: array
        minItems: 1
        items:
          $ref: '#/definitions/Sense'
      requiredSleepTime:
        description: |
          Time that character spend sleeping in minutes.
          By default it is 8h (480 minutes)
        type: integer
        minimum: 0
        default: 480
    required:
      - name
      - senses

  Party:
    description: A party of characters
    type: array
    minItems: 1
    items:
      $ref: '#/definitions/Character'

  PlanRequest:
    description: Body of a plan request.
    properties:
      maxTotalTimeSpent:
        description: Maximum total time spent in minutes.
        type: integer
        minimum: 60
        default: 720
      party:
        $ref: '#/definitions/Party'
    required:
      - maxTotalTimeSpent
      - party

  Watch:
    description: Details of a watch.
    properties:
      sleepingCharacters:
        description: List of PC names sleeping during the watch.
        type: array
        minItems: 1
        items:
          type: string
      watchfulCharacters:
        description: List of PC names watchful during the watch.
        type: array
        minItems: 1
        items:
          type: string
      length:
        description: Length of the watch in minutes
        type: integer
    required:
      - sleepingCharacters
      - watchfulCharacters
      - length

  Score:
    description: Score of a night watch proposal. A perfect soluction is one with 0 hard, 0 medium and 0 soft scores
    properties:
      initScore:
        type: integer
      hardScore:
        type: integer
      mediumScore:
        type: integer
      softScore:
        type: integer
      feasible:
        description: If solution is feasible (has 0 hard score)
        type: boolean

  Plan:
    description: Night watch plan
    properties:
      watchesSummary:
        type: array
        items:
          $ref: '#/definitions/Watch'
      totalTime:
        type: integer
      score:
         $ref: '#/definitions/Score'
    required:
      - watches
      - totalTime
      - score
