version: '3.7'

services:
  optimizer:
    build:
      context: .
    ports:
    - "3000:3000"
    environment:
    - PORT=3000
    depends_on:
    - swagger
  swagger:
    image: swaggerapi/swagger-ui
    ports:
    - "9002:8080"
    environment:
    - SWAGGER_JSON=/swagger/api.yml
    volumes:
    - type: bind
      source: ./api.yml
      target: /swagger/api.yml
