# Night Watch planner API
swagger: '2.0'
info:
  title: Night Watch Planner API
  description: Planner to optimize Night Watchs in RPGs
  version: "1.0.0"
host: localhost:3000
schemes:
  - http
basePath: /v1
produces:
  - application/json
paths:
  /optimize:
    post:
      summary: Rewatches an optimized nigth watch plan for the provided characters.
      description: Rewatches an optimized nigth watch plan for the provided characters.
      operationId: getOptimizedPlan
      parameters:
        - name: planRequest
          in: body
          description: Details of the plan request.
          required: true
          schema:
            $ref: '#/definitions/PlanRequest'

      produces:
        - application/json
      responses:
        200:
          description: Plan generated
          schema:
            $ref: '#/definitions/Plan'
        403:
          description: Bad request
          schema:
            properties:
              message:
                type: string
                description: Error message
definitions:
  Sense:
    description: Relevant senses that allows a _PC_ to be aware of intruders at a relevant distance.
    type: string
    default: Normal
    enum:
      - Blindsight
      - Darkvision
      - Low light
      - Normal
      - Scent

  Character:
    properties:
      name:
        type: string
      senses:
        type: array
        minItems: 1
        items:
          $ref: '#/definitions/Sense'
      requiredSleepTime:
        description: |
          Time that character spend sleeping in minutes.
          By default it is 8h (480 minutes)
        type: integer
        minimum: 1
        default: 480
    required:
      - name
      - senses

  Party:
    description: A party of characters
    type: array
    minItems: 1
    items:
      $ref: '#/definitions/Character'

  PlanRequest:
    description: Body of a plan request.
    properties:
      lengthOfWatch:
        description: Lenth of a watch in minutes.
        type: integer
        minimum: 1
        default: 60
      maxWatches:
        description: Maximum watches in which night watch divides.
        type: integer
        minimum: 1
        default: 8
      firstNightWatch:
        description: |
          First watch that happens in dark condition.
          The number of the first watch is one (not zero).
          By default all watches happen in dark condition.
        type: integer
        default: 1
        minimum: 1
      lastNightWatch:
        description: |
          Last watch that happens in dark condition.
          The number of the first watch is one (not zero).
          By default all watches after the first in dark condition happen also in dark condition.
        type: integer
        minimum: 1
      party:
        $ref: '#/definitions/Party'
    required:
      - lengthOfWatch
      - maxWatches
      - party

  Watch:
    description: Details of a watch.
    properties:
      sleepingCharacters:
        description: List of PC names sleeping during the watch.
        type: array
        minItems: 1
        items:
          type: string
      watchfulCharacters:
        description: List of PC names watchful during the watch.
        type: array
        minItems: 1
        items:
          type: string
      length:
        description: Length of the watch in minutes
        type: integer
    required:
      - sleepingCharacters
      - watchfulCharacters
      - length

  CharacterWatchSummary:
    description: Watch summary of a character
    properties:
      characterName:
        description: Name of the character
        type: string
      sleepingTime:
        description: Acumulated speeping time (in minutes) along the night
        type: integer
      maxConsecutiveSleepingTime:
        description: Maximum uninterrupted interval of time sleeping during the night
        type: integer
    required:
      - character
      - sleepingTime
      - maxConsecutiveSleepingTime

  Plan:
    description: Night watch plan
    properties:
      watches:
        type: array
        items:
          $ref: '#/definitions/Watch'
      watchSummary:
        description: Summary of the characters watch
        type: array
        items:
          $ref: '#/definitions/CharacterWatchSummary'
    required:
      - watches
