version: 2
jobs:
  install-client:
    working_directory: ~/night-watch-planner

    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - restore_cache:
          key: client-dependency-cache-{{ checksum "client/package.json" }}

      - run: cd ~/night-watch-planner/client && npm install

      - save_cache:
          paths:
            - ~/night-watch-planner/client/node_modules
          key: client-dependency-cache-{{ checksum "client/package.json" }}

  test-client:
    working_directory: ~/night-watch-planner

    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - restore_cache:
          key: client-dependency-cache-{{ checksum "client/package.json" }}

      - run: cd ~/night-watch-planner/client && npm run test:ci

  build-and-test-backend:

    working_directory: ~/night-watch-planner

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: circleci-night-watch-planner-{{ checksum "optimizer/pom.xml" }}

      - run: mvn -f optimizer/pom.xml dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-night-watch-planner-{{ checksum "optimizer/pom.xml" }}

      - run: mvn -f optimizer/pom.xml package

      - store_test_results:
          path: optimizer/target/surefire-reports

      - store_artifacts:
          path: optimizer/target/omptimizer-0.1.0-SNAPSHOT.jar

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test-backend
      - install-client
      - test-client:
          requires:
            - install-client
