server:
  port: 3000
client:
  url: ${NWP_CLIENT_URL}
logging:
  level:
    #ROOT: DEBUG
    org.optaplanner: debug
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
