export const CHARACTER_ADD = 'CHARACTER_ADD';
export const CHARACTER_REMOVE = 'CHARACTER_REMOVE';
export const CHARACTER_NAME_UPDATE = 'CHARACTER_NAME_UPDATE';
export const CHARACTER_SLEEP_TIME_INCREASE = 'CHARACTER_SLEEP_TIME_INCREASE';

export const MAX_TOTAL_TIME_SPENT_INCREASE = 'MAX_TOTAL_TIME_SPENT_INCREASE';
