export const ADD_CHARACTER = 'ADD_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
export const UPDATE_CHARACTER_NAME = 'UPDATE_CHARACTER_NAME';
export const ADD_SLEEP_TIME_TO_CHARACTER = 'ADD_SLEEP_TIME_TO_CHARACTER';

export const ADD_TIME_TO_MAX_TOTAL_TIME_SPENT = 'ADD_TIME_TO_MAX_TOTAL_TIME_SPENT';
